#!/usr/bin/env bash
set -euo pipefail

# variables
reset=$(tput sgr0)
red=$(tput setaf 1)
green=$(tput setaf 2)
yellow=$(tput setaf 3)

main(){
  # ...
}

debian_docker(){
  # ...
}

centos_docker(){
  # ...
}

post_config(){
  # ...
}

main
