#!/usr/bin/env bash
set -euo pipefail

reset=$(tput sgr0)
red=$(tput bold && tput setaf 1)
green=$(tput bold && tput setaf 2)
yellow=$(tput bold && tput setaf 3)
date_time=$(date +'%d-%m-%Y-T%H:%M:%S%z')
sudo_home=$(getent passwd "$SUDO_USER" | cut --delimiter=: --fields=6)

function error(){
  echo "[$date_time]: $*" >&2
}

# https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus
function install_prometheus(){
 echo "$yellow Installing Prometheus through the community Helm charts... $reset"
  if [[ -e /usr/local/bin/helm ]]
  then
    echo "$yellow Adding the Prometheus Communiy & Kube State Metrics repositories... $reset"
    helm repo add prometheus-community https://prometheus-community.github.io/helm-charts \
      --kubeconfig="$sudo_home"/.kube/config \
      --force-update \
      --debug
    helm repo add kube-state-metrics https://kubernetes.github.io/kube-state-metrics \
      --kubeconfig="$sudo_home"/.kube/config \
      --force-update \
      --debug
    helm repo update \
      --kubeconfig="$sudo_home"/.kube/config \
      --debug
    echo "$yellow Listing and searching for the charts in the Prometheus Communiy & Kube State Metrics repository... $reset"
    helm repo list \
      --kubeconfig="$sudo_home"/.kube/config \
      --output=table \
      --debug \
      | grep "https://prometheus-community.github.io/helm-charts"
    helm search repo prometheus \
      --kubeconfig="$sudo_home"/.kube/config \
      --output=table \
      --debug
    helm repo list \
      --kubeconfig="$sudo_home"/.kube/config \
      --output=table \
      --debug \
      | grep "https://kubernetes.github.io/kube-state-metrics"
    helm search repo kube-state-metrics \
      --kubeconfig="$sudo_home"/.kube/config \
      --output=table \
      --debug
    echo "$yellow Installing the Prometheus Community Helm Chart... $reset"
    helm install prometheus-community/prometheus \
      --kubeconfig="$sudo_home"/.kube/config \
      --output=table \
      --namespace=prometheus \
      --create-namespace \
      --atomic \
      --debug
    echo "$green Prometheus Community Helm Chart installation completed... $reset"
  else
    error "$red Please ensure that a Helm 3 client is located in the following path first > [ /usr/local/bin/helm ]... $reset"
    exit 1
  fi
}

install_prometheus "$@"
