#!/usr/bin/env bash
set -euo pipefail

reset=$(tput sgr0)
red=$(tput bold && tput setaf 1)
green=$(tput bold && tput setaf 2)
yellow=$(tput bold && tput setaf 3)
date_time=$(date +'%d-%m-%Y-T%H:%M:%S%z')
sudo_home=$(getent passwd "$SUDO_USER" | cut --delimiter=: --fields=6)

function error(){
  echo "[$date_time]: $*" >&2
}

# https://www.weave.works/docs/scope/latest/installing/#k8s
function weavescope(){
  if [[ -e /usr/bin/kubectl ]]
  then
    echo "$yellow Installing WeaveScope... $reset"
    kubectl apply --record \
                  --kubeconfig="$sudo_home"/.kube/config \
                  --filename="https://cloud.weave.works/k8s/scope.yaml?k8s-version=$(kubectl version | base64 | tr --delete '\n')"
    echo "$green WeaveScope installation complete... $reset"
  else
    error "$red Please ensure that kubectl is installed... $reset"
    exit 1
  fi
}

weavescope "$@"
