#!/usr/bin/env bash
set -euo pipefail

reset=$(tput sgr0)
red=$(tput bold && tput setaf 1)
green=$(tput bold && tput setaf 2)
yellow=$(tput bold && tput setaf 3)
date_time=$(date +'%d-%m-%Y-T%H:%M:%S%z')
working_directory=$(pwd)
sudo_home=$(getent passwd "$SUDO_USER" | cut --delimiter=: --fields=6)

function error(){
  echo "[$date_time]: $*" >&2
}

# https://github.com/kubernetes/dashboard#install
function kubernetes_dashboard(){
  if [[ -e /usr/bin/kubectl ]]
  then
    source "$working_directory"/observability/install_metrics
    echo "$yellow Installing Kubernetes dashboard... $reset"
    kubectl apply --record \
                  --kubeconfig="$sudo_home"/.kube/config \
                  --filename=https://raw.githubusercontent.com/kubernetes/dashboard/master/aio/deploy/recommended.yaml
    echo "$green Kubernetes dashboard installation complete... $reset"
  else
    error "$red Please ensure that kubectl is installed and the Kubernetes metrics server deployment script exists as it is a required dependency... $reset"
    exit 1
  fi
}

kubernetes_dashboard "$@"
