#!/usr/bin/env bash
set -euo pipefail

reset=$(tput sgr0)
red=$(tput bold && tput setaf 1)
green=$(tput bold && tput setaf 2)
yellow=$(tput bold && tput setaf 3)
date_time=$(date +'%d-%m-%Y-T%H:%M:%S%z')
working_directory=$(pwd)

function error(){
  echo "[$date_time]: $*" >&2
}

function main(){
  if [[ -e /usr/bin/rpm && -e /usr/bin/dnf && -e /usr/bin/yum && -e /etc/centos-release ]]
  then
    remove_containerd_prerequisites
    remove_containerd_centos
  elif [[ -e /usr/bin/apt && -e /usr/bin/dpkg && -e /etc/os-release && -e /etc/debian_version && ! -e /usr/bin/snap ]]
  then
    remove_containerd_prerequisites
    remove_containerd_debian
  else
    error "$red Please ensure that you are using CentOS or Debian... $reset"
    exit 1
  fi
}

function remove_containerd_prerequisites(){
  
}

function remove_containerd_centos(){
  # ...
  remove_containerd_configuration_file
}

function remove_containerd_debian(){
  # ...
  remove_containerd_configuration_file
}

function remove_containerd_configuration_file(){

}

main "$@"
