#!/usr/bin/env bash
set -euo pipefail

reset=$(tput sgr0)
red=$(tput bold && tput setaf 1)
green=$(tput bold && tput setaf 2)
yellow=$(tput bold && tput setaf 3)
date_time=$(date +'%d-%m-%Y-T%H:%M:%S%z')
sudo_home=$(getent passwd "$SUDO_USER" | cut --delimiter=: --fields=6)

function error(){
  echo "[$date_time]: $*" >&2
}

function main(){
  if [[ -e /usr/bin/rpm && -e /usr/bin/dnf && -e /usr/bin/yum && -e /etc/centos-release ]]
  then
    remove_kubernetes_prerequisites
    remove_kubernetes_centos
  elif [[ -e /usr/bin/apt && -e /usr/bin/dpkg && -e /etc/os-release && -e /etc/debian_version && ! -e /usr/bin/snap ]]
  then
    remove_kubernetes_prerequisites
    remove_kubernetes_debian
  else
    error "$red Please ensure that you are using CentOS or Debian... $reset"
    exit 1
  fi
}

function remove_kubernetes_prerequisites(){
  
}

function remove_kubernetes_centos(){
  
}

function remove_kubernetes_debian(){
  
}

main "$@"
