#!/usr/bin/env bash
set -euo pipefail

reset=$(tput sgr0)
red=$(tput setaf 1)
green=$(tput setaf 2)
yellow=$(tput setaf 3)
date_time=$(date +'%d-%m-%Y-T%H:%M:%S%z')
working_directory=$(pwd)

function error(){
  echo "[$date_time]: $*" >&2
}

function main(){
  if [[ -e /usr/bin/rpm && -e /usr/bin/dnf && -e /usr/bin/yum && -e /etc/centos-release ]]
  then
    docker_centos
  elif [[ -e /usr/bin/apt && -e /usr/bin/dpkg && -e /etc/os-release && -e /etc/debian_version && ! -e /usr/bin/snap ]]
  then
    docker_debian
  else
    error "$red Please ensure that you are using CentOS or Debian $reset"
    exit 1
  fi
}

function docker_centos(){
  echo "$yellow Removing older versions of Docker installed, if any... $reset"
  dnf remove --assumeyes docker \
                         docker-client \
                         docker-client-latest \
                         docker-common \
                         docker-latest \
                         docker-latest-logrotate \
                         docker-logrotate \
                         docker-engine
  echo "$yellow Setting up the stable repository for Docker CE... $reset"
  dnf install --assumeyes dnf-plugins-core
  dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  echo "$yellow Installing Docker CE... $reset"
  dnf update
  dnf install --assumeyes docker-ce \
                          docker-ce-cli \
                          containerd.io
  echo "$green Installation completed. $reset"
  docker_start
}


main "$@"
