#!/usr/bin/env bash
set -euo pipefail

reset=$(tput sgr0)
green=$(tput setaf 2)
yellow=$(tput setaf 3)
date_time=$(date +'%d-%m-%Y-T%H:%M:%S%z')
working_directory=$(pwd)
sudo_home=$(getent passwd "$SUDO_USER" | cut --delimiter=: --fields=6)

function error(){
  echo "[$date_time]: $*" >&2
}

# https://docs.projectcalico.org/getting-started/kubernetes
function calico_init(){
   echo "$yellow Initialising the control plane and allocating a pod network CIDR - 192.168.0.0/16 - for Calico... $reset"
   kubeadm init --pod-network-cidr=192.168.0.0/16 --ignore-preflight-errors=all
   source "$working_directory"/kubernetes/kubectl_configure
   echo "$yellow Installing Calico... $reset"
   sleep 3s
   kubectl apply --record --kubeconfig="$sudo_home"/.kube/config --filename=https://docs.projectcalico.org/manifests/calico.yaml
   echo "$green Calico Installation complete... $reset"
}

calico_init "$@"
