#!/usr/bin/env bash
set -euo pipefail

reset=$(tput sgr0)
red=$(tput setaf 1)
green=$(tput setaf 2)
yellow=$(tput setaf 3)
date_time=$(date +'%d-%m-%Y-T%H:%M:%S%z')
random_generated_password=$(pwgen --capitalize --secure --symbols -1 128)

function error(){
  echo "[$date_time]: $*" >&2
}

function main(){
  if [[ -e /usr/bin/pwgen ]]
  then
    weavenet_init
  else  
    if [[ -e /usr/bin/rpm && -e /usr/bin/dnf && -e /usr/bin/yum && -e /etc/centos-release ]]
    then
      echo "$yellow Ensuring pwgen is installed... $reset"
      dnf install --assumeyes pwgen
      weavenet_init
    elif [[ -e /usr/bin/apt && -e /usr/bin/dpkg && -e /etc/os-release && -e /etc/debian_version && ! -e /usr/bin/snap ]]
    then
      echo "$yellow Ensuring pwgen is installed... $reset"
      apt install --yes pwgen
      weavenet_init
    else
      error "$red Please ensure that you are using CentOS or Debian $reset"
      exit 1
    fi
  fi
}
